theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
completion-timeout = 5
completion-trigger-len = 1
rulers = [81]
auto-pairs = false
# end-of-line-diagnostics = "hint"
#
# [editor.inline-diagnostics]
# cursor-line = "hint"
# other-lines = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
goto-reference-include-declaration = false

[editor.whitespace.render]
tab = "all"
nbsp = "all"
nnbsp = "all"

[editor.indent-guides]
render = true
skip-levels = 1

[keys.normal]
g = { q = ":reflow" }
